services:

  postgres:
    image: postgres:15

    container_name: database-postgres-1

    restart: unless-stopped

    environment:
      POSTGRES_USER: omop
      POSTGRES_PASSWORD: omop
      POSTGRES_DB: omop

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:

  postgres_data: